# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1043, 730)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(0, 0, 255);\n"
"background-color: rgb(116, 118, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 60, 121, 581))
        self.listWidget.setStyleSheet("\n"
"background-color: rgb(183, 255, 194);")
        self.listWidget.setObjectName("listWidget")
        self.btn_dir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dir.setGeometry(QtCore.QRect(10, 10, 101, 41))
        self.btn_dir.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_dir.setObjectName("btn_dir")
        self.btn_left = QtWidgets.QPushButton(self.centralwidget)
        self.btn_left.setGeometry(QtCore.QRect(180, 580, 91, 61))
        self.btn_left.setStyleSheet("background-color: rgb(155, 255, 153);")
        self.btn_left.setObjectName("btn_left")
        self.btn_right = QtWidgets.QPushButton(self.centralwidget)
        self.btn_right.setGeometry(QtCore.QRect(320, 580, 91, 61))
        self.btn_right.setStyleSheet("background-color: rgb(177, 255, 165);")
        self.btn_right.setObjectName("btn_right")
        self.btn_flip = QtWidgets.QPushButton(self.centralwidget)
        self.btn_flip.setGeometry(QtCore.QRect(460, 580, 101, 61))
        self.btn_flip.setStyleSheet("background-color: rgb(160, 255, 166);")
        self.btn_flip.setObjectName("btn_flip")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 60, 831, 491))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.btn_sharp = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sharp.setGeometry(QtCore.QRect(600, 580, 111, 61))
        self.btn_sharp.setStyleSheet("background-color: rgb(172, 255, 185);")
        self.btn_sharp.setObjectName("btn_sharp")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(750, 580, 111, 61))
        self.pushButton_6.setStyleSheet("background-color: rgb(180, 255, 179);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(900, 580, 111, 61))
        self.btn_save.setStyleSheet("background-color: rgb(172, 255, 172);")
        self.btn_save.setObjectName("btn_save")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1043, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_dir.setText(_translate("MainWindow", "Папка"))
        self.btn_left.setText(_translate("MainWindow", "ліво"))
        self.btn_right.setText(_translate("MainWindow", "вправо "))
        self.btn_flip.setText(_translate("MainWindow", "дзеркало"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.btn_sharp.setText(_translate("MainWindow", "різкість "))
        self.pushButton_6.setText(_translate("MainWindow", "чб"))
        self.btn_save.setText(_translate("MainWindow", "зберегти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
